'''1. What is Python?

Python is a high-level, interpreted, general-purpose programming language known for its simple syntax and readability. It is widely used for web development, data analysis, AI, automation, and more.

2. Areas where Python is used

Python is used in many domains:

Web Development (e.g., Django, Flask)
Data Science & Analytics
Machine Learning & AI
Automation / Scripting
Game Development
Cybersecurity / Ethical Hacking
Desktop Applications
IoT (Internet of Things)
3. High-level vs Low-level language
High-Level Language	Low-Level Language
Easy to read/write	Hard to understand
Human-friendly	Machine-friendly
Portable	Machine dependent
Example: Python, Java	Example: Assembly, Machine code
4. What is an Interpreted Language?

An interpreted language executes code line-by-line using an interpreter, without converting the entire program into machine code at once.

👉 Example: Python

5. What is a Compiled Language?

A compiled language converts the entire program into machine code before execution using a compiler.

👉 Example: C, C++

6. What is a Statically Typed Language?

In statically typed languages, the data type of variables is defined at compile time.

👉 Example:

int x = 10;

👉 Example languages: C, C++, Java

7. What is a Dynamically Typed Language?

In dynamically typed languages, the data type is determined at runtime.

👉 Example:

x = 10
x = "Hello"

👉 Example: Python

8. What is Weakly Typed Language?

A weakly typed language allows implicit type conversion (type coercion).

👉 Example:

"5" + 5  // Output: "55"
9. What is Strongly Typed Language?

A strongly typed language does not allow implicit type conversion easily and enforces type rules strictly.

👉 Example (Python):

"5" + 5  # Error
10. What is .PYC file (Bytecode)?

A .pyc file is a compiled version of Python code (bytecode) stored for faster execution.

Created automatically by Python
Stored in __pycache__ folder
11. What is PVM?

PVM stands for Python Virtual Machine.

It executes the bytecode (.pyc)
It acts like an interpreter that runs Python programs
12. How Python internally works?

Step-by-step process:

You write code (.py file)
Python compiles it into bytecode (.pyc)
Bytecode is sent to PVM
PVM executes the instructions

👉 So:
Source Code → Bytecode → PVM → Output

13. What is PEP 8?

PEP 8 is the official style guide for Python code.

It defines:

Naming conventions
Indentation (4 spaces)
Line length (79 characters)
Code readability rules
14. What is PIP? What is its use?

PIP stands for “Pip Installs Packages”.

It is used to:

Install libraries
Upgrade packages
Remove packages

👉 Example:

pip install numpy
15. What is Bytecode and when is it created?

Bytecode is an intermediate code generated by Python.

It is not machine code
It is created automatically when you run a Python program
Stored as .pyc files

num=3
print (type(num))
num=True
print(type(num))
num=[1,2,3,4]
a=42
a/=5
print(a)
a//=5
print(a)

reference in python to variable 
a=4
b=4
print (id(a))
print (id(b))
a=5
print(id(a))  #the id will change of that program
print (id(b))


#ye  256 tak reference ko rkhta 

is  reference equal ha ya nhi memroy location
== value equal h ya nhi

list1= ["sachin","vishal"]
print("sachin" in list1)
print("sachin" not in list1)

s={1,2,3}
print(s)

student={"name": "chandan", "age":20}
print(student)

🔹 Why do we use None?
1. ✅ To Initialize a Variable (no value yet)

When you don’t have a value right now but will assign it later:

x = None
2. ✅ Function with No Return Value

If a function doesn’t return anything, it automatically returns None:

def greet():
    print("Hello")

result = greet()
print(result)   # Output: None
3. ✅ To Represent Missing or Empty Data

Used when data is not available:

user_age = None
4. ✅ As a Default Value in Functions
def display(name=None):
    if name is None:
        print("No name provided")
    else:
        print(name)
5. ✅ To Check Conditions

You can check if something has no value:

if x is None:
    print("No value assigned")
🔹 Important Points
None is not the same as:
0 (zero)
"" (empty string)
False

Always check using:

if x is None

(not ==)

✅ Simple Definition (Exam Ready)

None is a special data type in Python that represents the absence of a value or a null value.


a=10
b=10
print (a is  b)

list=[2,3,5]
print(list[0])
print(list[-1])


identation error in python 

b="python"
print ("x" is not  b)
x="x"
print(x is not b)

python string 

single quotes, double quotes, triple quotes

num='ram'
print(type(num))
n="ram"
a="""ram"""
print(type(n))
print(type(a))

a="sfjsak;fsflfjlsfjsljfljalsdjfslfjassunr-9et9-eu9wu r-0wer0rew0u0u0tu 0 u0ut-0u0u0u0u0v-0rw00-eut0eu0u0ewru0u0teur0u0\
    fefdgdogogojoj"
print(type(a))

a="""sfjsak;fsflfjlsfjsljfljalsdjfslfjassunr-9et9-eu9wu r-0wer0rew0u0u0tu 0 u0ut-0u0u0u0u0v-0rw00-eut0eu0u0ewru0u0teur0u0
    fefdgdogogojoj"""
print(type(a))

a="Hello0"
print(type(a))

name="sachin"
name1="sachin dr 4+4"
print (len(name))
print(len(name1))

n="python"
print(n[0])
print(n[-1])

n="ptdjf"
n[0]
this will print nothing vs code but in jupyter it print 'p'

slicing in sting sting[start:stop:step]
start:inclsive
stop:exclusive
end:defult is 1

name="python"
print(name[0:6:1])
print(name[::])
print(name[::2])
print(name[::1])

output:
python
python
pto
python

print(name[-6:0:1])  #print nothing

'''


# Immutable types:
# String (str)
# Tuple (tuple)
# Number (int, float)

# Mutable types (जो बदल सकते हैं):
# List (list)
# Dictionary (dict)
# Set (set)

#string methods

# string ="string"
# print(string.startswith("s"))
# output: true

#str="this is python programme"
# print(string.replace("python","jave"))
# print(string)

# str="this is my car"
# print(str.capitalize())
# output:This is my car

# str="This Is MY caR"
# print(str.casefold())
# output:this is my car

# text = "ß"   # German letter

# print(text.lower())     # ß
# print(text.casefold())  # ss

# 👉 Explanation:

# lower() → keeps ß as it is
# casefold() → converts it to "ss" (correct for comparison)
# 🧠 When to Use What?
# ✅ Use lower():
# Normal text formatting
# When working with simple English strings
# ✅ Use casefold():
# When doing case-insensitive comparisons
# When working with international (Unicode) text

# str="this is my car"
# print(str.center())
# string.center(length, fillchar)
# Parameters:
# length → Total length of the final string
# fillchar (optional) → Character used for padding (default is space " ")
# ✅ Basic Example
# text = "Hello"
# print(text.center(10))

# 👉 Output:

#   Hello   

# (Spaces added on both sides to make total length = 10)

# 🎯 Example with Custom Character
# text = "Hello"
# print(text.center(10, "*"))

# 👉 Output:

# **Hello***
# ⚠️ Important Points
# If length ≤ original string length, it returns the original string.
# text = "Hello"
# print(text.center(3))   # Hello
# fillchar must be only one character
# # ❌ Error
# text.center(10, "ab")
# 💡 Real-Life Use
# 1. Formatting Output
# print("Welcome".center(20, "-"))

# 👉 Output:

# ------Welcome-------

'''string.count(value, start, end)
Parameters:
value → The substring you want to count (required)
start → Starting index (optional)
end → Ending index (optional)
✅ Basic Example
text = "hello world"
print(text.count("o"))

👉 Output:

2
🎯 Counting a Word
text = "apple banana apple mango apple"
print(text.count("apple"))

👉 Output:

3
🔍 Using start and end
text = "hello hello hello"
print(text.count("hello", 0, 10))

👉 Output:

2

string.encode(encoding="utf-8", errors="strict")
Parameters:
encoding → Type of encoding (default is "utf-8")
errors → How to handle errors (strict, ignore, replace)
✅ Basic Example
text = "Hello"
result = text.encode()

print(result)

👉 Output:

b'Hello'

👉 "b" means it is now in bytes format

🎯 Example with Encoding Type
text = "Hello"
print(text.encode("utf-8"))

👉 Output:

b'Hello'
🔥 Example with Special Character
text = "हेलो"
print(text.encode("utf-8"))

👉 Output (bytes form):

b'\xe0\xa4\xb9\xe0\xa5\x87\xe0\xa4\xb2\xe0\xa5\x8b'
⚠️ Error Handling
1. strict (default)
text = "Hello😊"
print(text.encode("ascii"))  

👉 ❌ Error (emoji not supported in ASCII)

2. ignore
print(text.encode("ascii", "ignore"))

👉 Output:

b'Hello'
3. replace
print(text.encode("ascii", "replace"))

👉 Output:

b'Hello?'

string.endswith(value, start, end)
Parameters:
value → The substring you want to check
start (optional) → Start position
end (optional) → End position
✅ Basic Example
text = "hello world"
print(text.endswith("world"))

👉 Output:

True
❌ Example (False Case)
text = "hello world"
print(text.endswith("hello"))

👉 Output:

False
🎯 Using start and end
text = "hello world"
print(text.endswith("lo", 0, 5))

👉 Output:

True

(Checks only "hello" part)

🔥 Check Multiple Values (Tuple)
text = "file.pdf"
print(text.endswith((".pdf", ".doc")))

👉 Output:

True

string.expandtabs(tabsize)
Parameters:
tabsize (optional) → Number of spaces for each tab
Default value = 8
✅ Basic Example
text = "Hello\tWorld"
print(text.expandtabs())

👉 Output (default tabsize = 8):

Hello   World
🎯 Example with Custom Tab Size
text = "Hello\tWorld"
print(text.expandtabs(4))

👉 Output:

Hello   World

(Here tab is replaced with 4 spaces)

🔥 Multiple Tabs Example
text = "A\tB\tC"
print(text.expandtabs(4))

👉 Output:

A   B   C

string.find(value, start, end)
Parameters:
value → Substring to search
start (optional) → Starting index
end (optional) → Ending index
✅ Basic Example
text = "hello world"
print(text.find("world"))

👉 Output:

6
❌ If Substring Not Found
text = "hello"
print(text.find("x"))

👉 Output:

-1

👉 Important:

Returns -1 if not found (no error)
🎯 Using start and end
text = "hello hello"
print(text.find("hello", 1))

👉 Output:

6
🔁 Find First Occurrence Only
text = "apple apple apple"
print(text.find("apple"))

👉 Output:

0

string.format(value1, value2, ...)
✅ Basic Example
text = "My name is {}"
print(text.format("Chandan"))

👉 Output:

My name is Chandan
🎯 Multiple Values
text = "My name is {} and I am {} years old"
print(text.format("Chandan", 20))

👉 Output:

My name is Chandan and I am 20 years old
🔢 Using Index Numbers
text = "I like {0} and {1}"
print(text.format("apple", "mango"))

👉 Output:

I like apple and mango

👉 Reuse values:

print("I like {0} {0}".format("apple"))

👉 Output:

I like apple apple
🔤 Using Named Arguments
text = "My name is {name} and I am {age}"
print(text.format(name="Chandan", age=20))

👉 Output:

My name is Chandan and I am 20

string.format_map(mapping)
Parameter:
mapping → A dictionary (or any mapping object)
✅ Basic Example
data = {"name": "Chandan", "age": 20}

text = "My name is {name} and I am {age}"
print(text.format_map(data))

👉 Output:

My name is Chandan and I am 20
🎯 Difference from format()
Using format()
data = {"name": "Chandan", "age": 20}
text = "My name is {name} and I am {age}"

print(text.format(**data))

👉 Here we use ** to unpack dictionary

Using format_map()
print(text.format_map(data))

👉 No need to use **

string.index(value, start, end)
Parameters:
value → Substring to search
start (optional) → Starting index
end (optional) → Ending index
✅ Basic Example
text = "hello world"
print(text.index("world"))

👉 Output:

6
❌ If Substring Not Found
text = "hello"
print(text.index("x"))

👉 ❌ Error:

ValueError: substring not found

👉 Important:

Unlike find(), it does NOT return -1
It throws an error
🎯 Using start and end
text = "hello hello"
print(text.index("hello", 1))

👉 Output:

6
🔁 First Occurrence Only
text = "apple apple apple"
print(text.index("apple"))

👉 Output:

0

string.isalnum()

👉 No parameters

✅ Basic Example
text = "Hello123"
print(text.isalnum())

👉 Output:

True
❌ Example (False Case)
text = "Hello 123"
print(text.isalnum())

👉 Output:

False

👉 Because it contains a space

❌ Special Characters
text = "Hello@123"
print(text.isalnum())

👉 Output:

False

👉 Because @ is not allowed

⚠️ Important Points
Returns True or False
Only allows:
Letters (A–Z, a–z)
Numbers (0–9)
Does NOT allow:
Spaces ❌
Symbols ❌
Special characters ❌
'''

# string.isalpha()

# 👉 No parameters

# ✅ Basic Example
# text = "Hello"
# print(text.isalpha())

# 👉 Output:

# True
# ❌ Example (False Case)
# text = "Hello123"
# print(text.isalpha())

# 👉 Output:

# False

# 👉 Because it contains numbers

# ❌ With Space
# text = "Hello World"
# print(text.isalpha())

# 👉 Output:

# False

# 👉 Space is not allowed ❌

# ❌ With Special Characters
# text = "Hello@"
# print(text.isalpha())

# 👉 Output:

# False
# ⚠️ Important Points
# Returns True or False
# Only allows letters (A–Z, a–z)
# Does NOT allow:
# Numbers ❌
# Spaces ❌
# Symbols ❌

# string.isascii()

# 👉 No parameters

# ✅ Basic Example
# text = "Hello123"
# print(text.isascii())

# 👉 Output:

# True

# 👉 Because all characters are standard ASCII (A–Z, a–z, 0–9)

# ❌ Example (Non-ASCII)
# text = "हेलो"
# print(text.isascii())

# 👉 Output:

# False

# 👉 Hindi characters are not ASCII

# ❌ Emoji Example
# text = "Hello😊"
# print(text.isascii())

# 👉 Output:

# False

# 👉 Emoji is not ASCII

# ⚠️ Important Points
# Returns True or False
# ASCII range = characters with code 0–127
# Includes:
# Letters ✅
# Numbers ✅
# Symbols like @ # $ ✅
# Does NOT include:
# Unicode characters ❌
# Emojis ❌
# Regional languages ❌

# string.isdecimal()

# 👉 No parameters

# ✅ Basic Example
# text = "12345"
# print(text.isdecimal())

# 👉 Output:

# True
# ❌ Example (False Case)
# text = "123a"
# print(text.isdecimal())

# 👉 Output:

# False

# 👉 Because it contains a letter

# ❌ With Special Characters
# text = "123.45"
# print(text.isdecimal())

# 👉 Output:

# False

# 👉 . is not allowed

# ❌ Negative Number
# text = "-123"
# print(text.isdecimal())

# 👉 Output:

# False

# 👉 - is not allowed

# ⚠️ Important Points
# Returns True or False
# Only allows digits (0–9)
# Does NOT allow:
# Decimal point ❌
# Negative sign ❌
# Letters ❌

# string.isdigit()

# 👉 No parameters

# ✅ Basic Example
# text = "12345"
# print(text.isdigit())

# 👉 Output:

# True
# ❌ Example (False Case)
# text = "123a"
# print(text.isdigit())

# 👉 Output:

# False

# 👉 Because it contains a letter

# ❌ With Decimal Number
# text = "12.3"
# print(text.isdigit())

# 👉 Output:

# False

# 👉 . is not allowed

# ❌ Negative Number
# text = "-123"
# print(text.isdigit())

# 👉 Output:

# False

# 👉 - is not allowed

# 🔥 Special Case (Important)
# print("²".isdigit())

# 👉 Output:

# True

# 👉 Superscript numbers are also considered digits ✔️

# ⚠️ Important Points
# Returns True or False
# Allows:
# Digits (0–9) ✅
# Some Unicode numeric characters (like ²) ✅
# Does NOT allow:
# Decimal point ❌
# Negative sign ❌
# Letters ❌


# string.isidentifier()

# 👉 No parameters

# ✅ Basic Example
# text = "my_var"
# print(text.isidentifier())

# 👉 Output:

# True
# ❌ Invalid Identifier Examples
# print("123var".isidentifier())   # False
# print("my-var".isidentifier())   # False
# print("my var".isidentifier())   # False

# 👉 Reasons:

# Cannot start with a number ❌
# No special characters like - ❌
# No spaces ❌
# ⚠️ Rules for Valid Identifier

# A string is a valid identifier if:

# Starts with a letter (a–z, A–Z) or underscore _
# Can contain:
# Letters ✅
# Digits ✅
# Underscore _ ✅
# Cannot contain:
# Spaces ❌
# Special characters (@ # - $) ❌
# Cannot be a keyword

# string.islower()

# 👉 No parameters

# ✅ Basic Example
# text = "hello"
# print(text.islower())

# 👉 Output:

# True
# ❌ Example (False Case)
# text = "Hello"
# print(text.islower())

# 👉 Output:

# False

# 👉 Because H is uppercase

# ⚠️ Important Rule
# It checks only letters
# Other characters (numbers, symbols) are ignored
# 🎯 Example with Numbers & Symbols
# text = "hello123"
# print(text.islower())

# 👉 Output:

# True

# ✔️ Numbers don’t affect the result

# ❌ Mixed Case
# text = "hello World"
# print(text.islower())

# 👉 Output:

# False
# ⚠️ Edge Case
# text = "12345"
# print(text.islower())

# 👉 Output:

# False

# 👉 Because there are no letters

# string.isnumeric()

# 👉 No parameters

# ✅ Basic Example
# text = "12345"
# print(text.isnumeric())

# 👉 Output:

# True
# ❌ Example (False Case)
# text = "123a"
# print(text.isnumeric())

# 👉 Output:

# False
# 🔥 Special Numeric Characters
# print("½".isnumeric())   # True
# print("²".isnumeric())   # True

# 👉 Output:

# True
# True

# ✔️ Accepts:

# Fractions (½)
# Superscripts (²)
# Other numeric Unicode characters
# ❌ Decimal & Negative Numbers
# print("12.5".isnumeric())   # False
# print("-123".isnumeric())   # False

# 👉 Because:

# . and - are not numeric characters 

# string.isprintable()

# 👉 No parameters

# ✅ Basic Example
# text = "Hello 123"
# print(text.isprintable())

# 👉 Output:

# True
# ❌ Example (Non-Printable Characters)
# text = "Hello\nWorld"
# print(text.isprintable())

# 👉 Output:

# False

# 👉 Because \n (newline) is not printable

# 🔥 More Examples
# print("Hello\tWorld".isprintable())  # False (\t is tab)
# print("Hello World!".isprintable()) # True
# ⚠️ Important Points
# Returns True or False
# Printable characters include:
# Letters ✅
# Numbers ✅
# Symbols ✅
# Space ✅
# Non-printable characters:
# \n (newline) ❌
# \t (tab) ❌
# \r (carriage return) ❌

# string.isspace()

# 👉 No parameters

# ✅ Basic Example
# text = "   "
# print(text.isspace())

# 👉 Output:

# True
# ❌ Example (False Case)
# text = "  a  "
# print(text.isspace())

# 👉 Output:

# False

# 👉 Because it contains a letter

# 🔥 Whitespace Characters

# Whitespace includes:

# Space " "
# Tab \t
# Newline \n
# Carriage return \r

# string.istitle()

# 👉 No parameters

# ✅ Basic Example
# text = "Hello World"
# print(text.istitle())

# 👉 Output:

# True
# ❌ Example (False Case)
# text = "hello World"
# print(text.istitle())

# 👉 Output:

# False

# 👉 Because first word is not capitalized

# ❌ Another False Case
# text = "Hello world"
# print(text.istitle())

# 👉 Output:

# False

# 👉 Because second word is not capitalized

# string.isupper()

# 👉 No parameters

# ✅ Basic Example
# text = "HELLO"
# print(text.isupper())

# 👉 Output:

# True
# ❌ Example (False Case)
# text = "Hello"
# print(text.isupper())

# 👉 Output:

# False

# 👉 Because it contains lowercase letters

# 🎯 With Numbers & Symbols
# text = "HELLO123"
# print(text.isupper())

# 👉 Output:

# True

# ✔️ Numbers and symbols are ignored

# ❌ Mixed Case
# text = "HELLO World"
# print(text.isupper())

# 👉 Output:

# False
# ⚠️ Edge Case
# text = "12345"
# print(text.isupper())

# 👉 Output:

# False

# 👉 Because there are no letters

# ⚠️ Important Points
# Returns True or False
# Checks only letters
# Non-letter characters are ignored
# Must have at least one letter

# separator.join(iterable)
# Parameters:
# separator → The string used to join elements
# iterable → List, tuple, etc. (must contain strings)
# ✅ Basic Example
# words = ["Hello", "World"]
# result = " ".join(words)

# print(result)

# 👉 Output:

# Hello World
# 🎯 Using Different Separators
# words = ["apple", "banana", "mango"]

# print(",".join(words))   # apple,banana,mango
# print("-".join(words))   # apple-banana-mango
# 🔥 Join Characters of a String
# text = "ABC"
# print("-".join(text))

# 👉 Output:

# A-B-C
# ❌ Error Case
# data = ["apple", 1, "mango"]
# print(",".join(data))

# 👉 ❌ Error because 1 is not a string

# ✔️ Fix:

# data = ["apple", "1", "mango"]
# print(",".join(data))

# string.ljust(width, fillchar)
# Parameters:
# width → Total length of the final string
# fillchar (optional) → Character used for padding (default = space " ")
# ✅ Basic Example
# text = "Hello"
# print(text.ljust(10))

# 👉 Output:

# Hello     

# (Spaces added on the right)

# 🎯 Example with Custom Character
# text = "Hello"
# print(text.ljust(10, "*"))

# 👉 Output:

# Hello*****
# ⚠️ Important Points
# If width ≤ original length, original string is returned
# text = "Hello"
# print(text.ljust(3))   # Hello
# fillchar must be only one character
# # ❌ Error
# text.ljust(10, "ab")
# 🔥 Compare with center() and rjust()
# Method	Alignment
# ljust()	Left
# rjust()	Right
# center()	Center

# string.lower()

# 👉 No parameters

# ✅ Basic Example
# text = "HELLO"
# print(text.lower())

# 👉 Output:

# hello
# 🎯 Mixed Case Example
# text = "HeLLo WoRLd"
# print(text.lower())

# 👉 Output:

# hello world
# ⚠️ Important Points
# Converts only uppercase letters → lowercase
# Other characters remain unchanged
# text = "Hello123!"
# print(text.lower())

# 👉 Output:

# hello123!

# string.lstrip(characters)
# characters → optional
# Default: removes spaces (whitespace)
# 🔹 Examples
# 1. Remove spaces from left
# text = "   hello world"
# print(text.lstrip())

# 👉 Output:

# hello world
# 2. Remove specific characters
# text = "###hello"
# print(text.lstrip("#"))

# 👉 Output:

# hello
# 3. Multiple characters
# text = "@@!!hello"
# print(text.lstrip("@!"))

# 👉 Output:

# hello
# 🔴 Important point

# lstrip() removes any matching characters, not a fixed string.

# text = "abcxyzhello"
# print(text.lstrip("abcxyz"))

# 👉 Output:

# hello

# (It removes all combinations of a, b, c, x, y, z from the left)

# str.maketrans(x, y, z)
# x → characters to replace
# y → characters to replace with
# z → characters to remove (optional)
# 🔹 Example 1: Replace characters
# text = "hello"
# table = str.maketrans("h", "y")
# print(text.translate(table))

# 👉 Output:

# yello
# 🔹 Example 2: Replace multiple characters
# text = "apple"
# table = str.maketrans("ap", "xy")
# print(text.translate(table))

# 👉 Output:

# xyyle
# 🔹 Example 3: Remove characters
# text = "hello123"
# table = str.maketrans("", "", "123")
# print(text.translate(table))

# 👉 Output:

# hello
# 🔹 Example 4: Using dictionary
# text = "hello"
# table = str.maketrans({"h": "H", "e": "E"})
# print(text.translate(table))

# 👉 Output:

# HEllo
# 🔴 Important Points
# maketrans() does not change string directly
# It creates a mapping table
# You must use it with translate()
# 🔹 Simple Flow
# maketrans() → create table  
# translate() → apply changes

'''string.partition(separator)
🔹 What it returns

It returns a tuple of 3 parts:

(before_separator, separator, after_separator)
🔹 Example 1
text = "hello world"
result = text.partition(" ")
print(result)

👉 Output:

('hello', ' ', 'world')
🔹 Example 2
text = "apple-banana-orange"
print(text.partition("-"))

👉 Output:

('apple', '-', 'banana-orange')
🔹 Example 3 (separator not found)
text = "hello"
print(text.partition("x"))

👉 Output:

('hello', '', '')
🔴 Important Points
Splits only at the first occurrence
Always returns 3 values (tuple)
If separator not found → last two values are empty

string.removeprefix(prefix)
🔹 Example 1
text = "unhappy"
print(text.removeprefix("un"))

👉 Output:

happy
🔹 Example 2
text = "hello world"
print(text.removeprefix("hello "))

👉 Output:

world
🔹 Example 3 (prefix not found)
text = "python"
print(text.removeprefix("java"))

👉 Output:

python
🔴 Important Points
Removes only if prefix matches exactly
If not matched → returns original string
Works only on starting part (left side)

string.removesuffix(suffix)
🔹 Examples
1. Basic example
text = "playing"
print(text.removesuffix("ing"))

👉 Output:

play
2. Remove word from end
text = "hello world"
print(text.removesuffix(" world"))

👉 Output:

hello
3. Suffix not found
text = "python"
print(text.removesuffix("java"))

👉 Output:

python
🔴 Important Points
Removes only if suffix matches exactly
If not matched → returns original string
Works only on ending (right side)

string.replace(old, new, count)
old → substring to be replaced
new → new substring
count → (optional) number of replacements
🔹 Examples
1. Basic replace
text = "hello world"
print(text.replace("world", "python"))

👉 Output:

hello python
2. Replace multiple occurrences
text = "apple apple apple"
print(text.replace("apple", "mango"))

👉 Output:

mango mango mango
3. Replace with count
text = "apple apple apple"
print(text.replace("apple", "mango", 2))

👉 Output:

mango mango apple
4. Replace character
text = "banana"
print(text.replace("a", "o"))

👉 Output:

bonono
🔴 Important Points
Strings are immutable → original string does not change
Returns a new string
Case-sensitive ("Hello" ≠ "hello")

string.rfind(substring, start, end)
substring → value to search
start, end → optional range
🔹 What it returns
Returns the last index of the substring
If not found → returns -1
🔹 Examples
1. Basic example
text = "hello world hello"
print(text.rfind("hello"))

👉 Output:

12
2. Substring not found
text = "python"
print(text.rfind("java"))

👉 Output:

-1
3. Using range
text = "hello hello hello"
print(text.rfind("hello", 0, 10))

👉 Output:

6
🔴 Important Points
Searches from right to left
Returns index (position), not the substring
Does not give error if not found (returns -1)

string.rindex(substring, start, end)
substring → value to search
start, end → optional range
🔹 What it returns
Returns the last index of the substring
If not found → ❌ gives error
🔹 Examples
1. Basic example
text = "hello world hello"
print(text.rindex("hello"))

👉 Output:

12
2. Using range
text = "hello hello hello"
print(text.rindex("hello", 0, 10))

👉 Output:

6
3. Substring not found
text = "python"
print(text.rindex("java"))

👉 Output:

ValueError: substring not found
🔴 Important Points
Searches from right to left
Returns index (position)
❗ Gives error if not found

string.rjust(width, fillchar)
width → total length of the final string
fillchar → optional character (default = space)
🔹 Examples
1. Basic example (spaces)
text = "hello"
print(text.rjust(10))

👉 Output:

     hello
2. Using custom character
text = "hello"
print(text.rjust(10, "*"))

👉 Output:

*****hello
3. Width smaller than string
text = "hello"
print(text.rjust(3))

👉 Output:

hello

(No change because width < string length)

🔴 Important Points
Padding is added on the left
Does not modify original string
Returns a new string
fillchar must be only one character

string.rpartition(separator)
🔹 What it returns

It returns a tuple of 3 parts:

(before_separator, separator, after_separator)
🔹 Examples
1. Basic example
text = "hello world hello"
print(text.rpartition(" "))

👉 Output:

('hello world', ' ', 'hello')
2. Another example
text = "apple-banana-orange"
print(text.rpartition("-"))

👉 Output:

('apple-banana', '-', 'orange')
3. Separator not found
text = "hello"
print(text.rpartition("x"))

👉 Output:

('', '', 'hello')
🔴 Important Points
Splits from the rightmost occurrence
Always returns 3 values (tuple)
If separator not found → first two values are empty

string.rsplit(separator, maxsplit)
separator → optional (default = space)
maxsplit → number of splits
🔹 Examples
1. Basic example
text = "hello world python"
print(text.rsplit())

👉 Output:

['hello', 'world', 'python']
2. Split from right
text = "a-b-c-d"
print(text.rsplit("-", 1))

👉 Output:

['a-b-c', 'd']
3. Multiple splits
text = "a-b-c-d"
print(text.rsplit("-", 2))

👉 Output:

['a-b', 'c', 'd']
🔴 Important Points
Works like split() but starts from right side
Returns a list
Useful when you only want to split last few parts
🔹 Difference from split()
text = "a-b-c-d"

print(text.split("-", 1))   # from left
print(text.rsplit("-", 1))  # from right

string.rstrip(characters)
characters → optional
Default: removes spaces (whitespace)
🔹 Examples
1. Remove spaces from right
text = "hello world   "
print(text.rstrip())

👉 Output:

hello world
2. Remove specific characters
text = "hello!!!"
print(text.rstrip("!"))

👉 Output:

hello
3. Multiple characters
text = "hello@@!!"
print(text.rstrip("@!"))

👉 Output:

hello
🔴 Important Point

rstrip() removes any matching characters, not an exact suffix.

text = "testinggg"
print(text.rstrip("g"))

👉 Output:

testin

string.split(separator, maxsplit)
separator → optional (default = space)
maxsplit → number of splits
🔹 Examples
1. Default split (by space)
text = "hello world python"
print(text.split())

👉 Output:

['hello', 'world', 'python']
2. Using a separator
text = "apple,banana,orange"
print(text.split(","))

👉 Output:

['apple', 'banana', 'orange']
3. Using maxsplit
text = "a-b-c-d"
print(text.split("-", 2))

👉 Output:

['a', 'b', 'c-d']
4. No separator found
text = "hello"
print(text.split(","))

👉 Output:

['hello']
🔴 Important Points
Returns a list
Default splits on whitespace
Does not modify original string
Works from left side'''

# string.splitlines(keepends)
# keepends → optional (default = False)
# False → removes newline characters
# True → keeps newline characters
# 🔹 Examples
# 1. Basic example
# text = "hello\nworld\npython"
# print(text.splitlines())

# 👉 Output:

# ['hello', 'world', 'python']
# 2. Keep newline characters
# text = "hello\nworld\npython"
# print(text.splitlines(True))

# 👉 Output:

# ['hello\n', 'world\n', 'python']
# 3. Works with different line breaks
# text = "hello\r\nworld\npython"
# print(text.splitlines())

# 👉 Output:

# ['hello', 'world', 'python']
# 🔴 Important Points
# Splits on line boundaries (\n, \r, \r\n)
# Returns a list
# Useful for reading multi-line text or files

'''string.startswith(value, start, end)
value → prefix to check
start, end → optional range
🔹 What it returns
✅ True → if string starts with given value
❌ False → otherwise
🔹 Examples
1. Basic example
text = "hello world"
print(text.startswith("hello"))

👉 Output:

True
2. False case
text = "hello world"
print(text.startswith("world"))

👉 Output:

False
3. Using start index
text = "hello world"
print(text.startswith("world", 6))

👉 Output:

True
4. Multiple values (tuple)
text = "python"
print(text.startswith(("py", "ja")))

👉 Output:

True
🔴 Important Points
Case-sensitive ("Hello" ≠ "hello")
Can check multiple prefixes using tuple
Returns boolean (True/False)
🔹 Related methods
endswith() → checks ending
find() → finds position

string.strip(characters)
🔹 Examples
1. Remove spaces
text = "   hello world   "
print(text.strip())

👉 Output:

hello world
2. Remove specific characters
text = "###hello###"
print(text.strip("#"))

👉 Output:

hello
3. Multiple characters
text = "@@!!hello!!@@"
print(text.strip("@!"))

👉 Output:

hello
🔴 Important Point

strip() removes any matching characters, not an exact word.

🔹 Related methods
lstrip() → left side
rstrip() → right side

string.swapcase()
🔹 Examples
1. Basic example
text = "Hello World"
print(text.swapcase())

👉 Output:

hELLO wORLD
2. Mixed characters
text = "PyThOn123"
print(text.swapcase())

👉 Output:

pYtHoN123
🔴 Important Points
Uppercase → lowercase
Lowercase → uppercase
Numbers and symbols remain unchanged
Returns a new string (original string stays same)

string.title()
🔹 Examples
1. Basic example
text = "hello world"
print(text.title())

👉 Output:

Hello World
2. Mixed case
text = "pYtHoN pRoGrAmMiNg"
print(text.title())

👉 Output:

Python Programming
3. With numbers/symbols
text = "hello123 world"
print(text.title())

👉 Output:

Hello123 World
🔴 Important Points
Capitalizes first letter of each word
Converts rest of letters to lowercase
Returns a new string
Words are separated by spaces or special characters

string.translate(table)
table → created using str.maketrans()
🔹 Example 1: Replace characters
text = "hello"
table = str.maketrans("h", "y")

print(text.translate(table))

👉 Output:

yello
🔹 Example 2: Replace multiple characters
text = "apple"
table = str.maketrans("ap", "xy")

print(text.translate(table))

👉 Output:

xyyle
🔹 Example 3: Remove characters
text = "hello123"
table = str.maketrans("", "", "123")

print(text.translate(table))

👉 Output:

hello
🔹 Example 4: Using dictionary
text = "hello"
table = str.maketrans({"h": "H", "e": "E"})

print(text.translate(table))

👉 Output:

HEllo
🔴 Important Points
translate() does not work alone
Needs a translation table
Returns a new string (original unchanged)

string.upper()
🔹 Examples
1. Basic example
text = "hello world"
print(text.upper())

👉 Output:

HELLO WORLD
2. Mixed characters
text = "PyThOn123"
print(text.upper())

👉 Output:

PYTHON123
🔴 Important Points
Converts all lowercase → uppercase
Numbers and symbols remain unchanged
Returns a new string (original does not change)

string.zfill(width)
width → total length of the final string
🔹 Examples
1. Basic example
text = "42"
print(text.zfill(5))

👉 Output:

00042
2. No change if length is already enough
text = "hello"
print(text.zfill(3))

👉 Output:

hello
3. With negative numbers
text = "-42"
print(text.zfill(5))

👉 Output:

-0042
🔴 Important Points
Adds zeros on the left side only
Works with strings (not directly numbers)
Keeps sign (+ or -) in front

__add__() in Python

__add__() is a special (dunder) method used to define the behavior of the + operator.

✅ What it does

It is called when you use:

a + b

👉 Internally, Python does:

a.__add__(b)
🔹 Example 1: With strings
a = "Hello "
b = "World"

print(a + b)

👉 Output:

Hello World
🔹 Example 2: With numbers
a = 5
b = 3

print(a + b)

👉 Output:

8
🔹 Example 3: Custom class
class Number:
    def __init__(self, value):
        self.value = value

    def __add__(self, other):
        return Number(self.value + other.value)

n1 = Number(10)
n2 = Number(20)

result = n1 + n2
print(result.value)

👉 Output:

30
🔴 Important Points
__add__() defines how + works
Used in operator overloading
Works for:
numbers
strings
lists
custom objects
🔹 Quick Summary
a + b  →  a.__add__(b)
🔹 Related methods
__sub__() → -
__mul__() → *
__truediv__() → /

It keeps a dictionary of variable names and their data types.

🔹 Example 1: Function annotations
def add(a: int, b: int) -> int:
    return a + b

print(add.__annotations__)

👉 Output:

{'a': <class 'int'>, 'b': <class 'int'>, 'return': <class 'int'>}
🔹 Example 2: Variable annotations
x: int = 10
y: str = "hello"

print(__annotations__)

👉 Output:

{'x': <class 'int'>, 'y': <class 'str'>}
🔹 Example 3: Class annotations
class Person:
    name: str
    age: int

print(Person.__annotations__)

👉 Output:

{'name': <class 'str'>, 'age': <class 'int'>}
🔴 Important Points
Used for type hinting (PEP 484)
Stored as a dictionary
Does not enforce types (Python is still dynamic)
Helps in:
readability
debugging
tools like IDEs & linters

It returns the class (type) of an object.

🔹 Example 1: Basic usage
x = 10
print(x.__class__)

👉 Output:

<class 'int'>
🔹 Example 2: With string
text = "hello"
print(text.__class__)

👉 Output:

<class 'str'>
🔹 Example 3: Custom class
class Person:
    pass

p = Person()
print(p.__class__)

👉 Output:

<class '__main__.Person'>
🔹 Same as type()
x = 5
print(type(x))
print(x.__class__)

👉 Both give:

<class 'int'>
🔴 Important Points
__class__ shows the class of an object
Works for all objects (int, str, list, custom objects)
Similar to type()
Mostly used in advanced Python / OOP

__contains__() is a special (dunder) method used to define how the in operator works.

✅ What it does

When you write:

item in container

👉 Python internally calls:

container.__contains__(item)
🔹 Example 1: With list
nums = [1, 2, 3, 4]
print(2 in nums)

👉 Output:

True
🔹 Example 2: With string
text = "hello"
print("e" in text)

👉 Output:

True
🔹 Example 3: Custom class
class MyList:
    def __init__(self, data):
        self.data = data

    def __contains__(self, item):
        return item in self.data

obj = MyList([10, 20, 30])

print(20 in obj)

👉 Output:

True
🔴 Important Points
Defines behavior of in operator
Returns True / False
Used in lists, strings, sets, dictionaries
Can be customized in your own classes

__delattr__() is a special (dunder) method used to delete an attribute from an object.

✅ What it does

When you write:

del obj.attribute

👉 Python internally calls:

obj.__delattr__("attribute")
🔹 Example 1: Basic usage
class Person:
    def __init__(self):
        self.name = "Chandan"

p = Person()
del p.name

print(hasattr(p, "name"))

👉 Output:

False
🔹 Example 2: Custom behavior
class Person:
    def __init__(self):
        self.name = "Chandan"

    def __delattr__(self, attr):
        print(f"Deleting {attr}")
        super().__delattr__(attr)

p = Person()
del p.name

👉 Output:

Deleting name
🔴 Important Points
Used when deleting attributes with del
You can control or customize deletion behavior
Usually calls super().__delattr__(attr) to actually delete

'''

'''__dict__ is a special attribute that stores all attributes (variables) of an object or class in the form of a dictionary.

✅ What it does

It shows the data inside an object.

🔹 Example 1: Object attributes
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

p = Person("Chandan", 20)

print(p.__dict__)

👉 Output:

{'name': 'Chandan', 'age': 20}
🔹 Example 2: Class attributes
class Student:
    school = "ABC School"

print(Student.__dict__)

👉 Output (shortened):

{
 'school': 'ABC School',
 ...
}
🔹 Example 3: Modify using __dict__
p = Person("Chandan", 20)

p.__dict__["age"] = 25
print(p.age)

👉 Output:

25
🔴 Important Points
Stores attributes in key-value pair
Works for:
objects
classes
Can be used to inspect or modify data
Not all objects have __dict__ (e.g., some built-in types)

__dir__() is a special (dunder) method used to list all attributes and methods of an object.

✅ What it does

When you use:

dir(obj)

👉 Python internally calls:

obj.__dir__()
🔹 Example 1: Basic usage
x = 10
print(dir(x))

👉 Output (shortened):

['__add__', '__class__', '__str__', ...]
🔹 Example 2: Custom class
class Person:
    def __init__(self):
        self.name = "Chandan"
        self.age = 20

p = Person()
print(dir(p))

👉 Output includes:

['age', 'name', '__class__', '__init__', ...]
🔹 Example 3: Customizing __dir__()
class Person:
    def __dir__(self):
        return ["name", "age", "custom_method"]

p = Person()
print(dir(p))

👉 Output:

['name', 'age', 'custom_method']
🔴 Important Points
Used to inspect object properties
Returns a list of attribute names
Can be customized in classes
Helpful for debugging and exploration
    
__doc__ is a special attribute used to store the documentation string (docstring) of a module, class, function, or method.

✅ What it does

It shows the description written inside triple quotes (""" """).

🔹 Example 1: Function docstring
def add(a, b):
    """This function adds two numbers"""
    return a + b

print(add.__doc__)

👉 Output:

This function adds two numbers
🔹 Example 2: Class docstring
class Person:
    """This class represents a person"""
    
print(Person.__doc__)

👉 Output:

This class represents a person
🔹 Example 3: Module docstring
"""This is a simple Python program"""

print(__doc__)

👉 Output:

This is a simple Python program
🔴 Important Points
Stored in __doc__ attribute
Written using triple quotes
Helps in documentation and readability
Used by tools like help()

__eq__() is a special (dunder) method used to define the behavior of the == (equality) operator.

✅ What it does

When you write:

a == b

👉 Python internally calls:

a.__eq__(b)
🔹 Example 1: With numbers
print(5 == 5)

👉 Output:

True
🔹 Example 2: With strings
print("hello" == "hello")

👉 Output:

True
🔹 Example 3: Custom class
class Person:
    def __init__(self, age):
        self.age = age

    def __eq__(self, other):
        return self.age == other.age

p1 = Person(20)
p2 = Person(20)

print(p1 == p2)

👉 Output:

True
🔴 Important Points
Defines behavior of == operator
Returns True / False
Used in operator overloading
Without __eq__(), objects are compared by memory address

__format__() is a special (dunder) method used to control how an object is formatted as a string.

✅ What it does

When you use:

format(obj, spec)

or

f"{obj:spec}"

👉 Python internally calls:

obj.__format__(spec)
🔹 Example 1: Basic usage
x = 123
print(format(x, "d"))

👉 Output:

123
🔹 Example 2: Using f-string
x = 3.14159
print(f"{x:.2f}")

👉 Output:

3.14
🔹 Example 3: Custom class
class Person:
    def __init__(self, name):
        self.name = name

    def __format__(self, format_spec):
        return f"Name: {self.name}"

p = Person("Chandan")
print(format(p, ""))

👉 Output:

Name: Chandan
🔴 Important Points
Used for string formatting
Works with:
format() function
f-strings (f"{x}")
You can customize output for your objects

__ge__() is a special (dunder) method used to define the behavior of the >= (greater than or equal to) operator.

✅ What it does

When you write:

a >= b

👉 Python internally calls:

a.__ge__(b)
🔹 Example 1: With numbers
print(5 >= 3)

👉 Output:

True
🔹 Example 2: With strings
print("b" >= "a")

👉 Output:

True
🔹 Example 3: Custom class
class Person:
    def __init__(self, age):
        self.age = age

    def __ge__(self, other):
        return self.age >= other.age

p1 = Person(25)
p2 = Person(20)

print(p1 >= p2)

👉 Output:

True
🔴 Important Points
Defines behavior of >= operator
Returns True / False
Used in operator overloading
Without it, comparison may fail for custom objects

__getattribute__() is a special (dunder) method used to control how attributes are accessed from an object.

✅ What it does

Whenever you access:

obj.attribute

👉 Python internally calls:

obj.__getattribute__("attribute")
🔹 Example 1: Basic usage
class Person:
    def __init__(self):
        self.name = "Chandan"

p = Person()
print(p.name)

👉 Output:

Chandan

(Internally uses __getattribute__)

🔹 Example 2: Custom behavior
class Person:
    def __init__(self):
        self.name = "Chandan"

    def __getattribute__(self, attr):
        print(f"Accessing {attr}")
        return super().__getattribute__(attr)

p = Person()
print(p.name)

👉 Output:

Accessing name
Chandan
🔴 Important Points
Called every time an attribute is accessed
Must use super().__getattribute__(attr) to avoid infinite loop
Very powerful but dangerous if misused
⚠️ Common Mistake (Infinite Recursion)
def __getattribute__(self, attr):
    return self.attr   # ❌ WRONG (causes infinite loop)
🔹 Difference from __getattr__()
Method	When called
__getattribute__()	Always
__getattr__()	Only if attribute not found

__getitem__() is a special (dunder) method used to define how indexing and slicing works.

✅ What it does

When you write:

obj[key]

👉 Python internally calls:

obj.__getitem__(key)
🔹 Example 1: With list
nums = [10, 20, 30]
print(nums[1])

👉 Output:

20
🔹 Example 2: Custom class (indexing)
class MyList:
    def __init__(self, data):
        self.data = data

    def __getitem__(self, index):
        return self.data[index]

obj = MyList([1, 2, 3])

print(obj[0])

👉 Output:

1
🔹 Example 3: Slicing support
class MyList:
    def __init__(self, data):
        self.data = data

    def __getitem__(self, index):
        return self.data[index]

obj = MyList([1, 2, 3, 4, 5])

print(obj[1:4])

👉 Output:

[2, 3, 4]
🔴 Important Points
Used for indexing ([])
Works with:
lists
tuples
strings
dictionaries
custom objects
Supports both single index and slicing

'''

#string formating

# name = "Chandan"
# age = 20

# print("My name is %s and I am %d years old" % (name, age))

#Common specifiers:
# %s → string
# %d → integer
# %f → float
# pi = 3.14159
# print("Value of pi is %.2f" % pi) 
    # 2 decimal places



# name = "Chandan"
# age = 20
# print("My name is {} and I am {}".format(name, age))

# Using index:
# print("My name is {0} and I am {1}".format(name, age))
# Using keywords:
#print("My name is {n} and I am {a}".format(n="Chandan", a=20))
# Formatting numbers:
# num = 12.34567
# print("Number: {:.2f}".format(num))  # 2 decimal places


# name = "Chandan"
# age = 20
# print(f"My name is {name} and I am {age} years old")

# Expressions inside f-string:
# a = 10
# b = 5
# print(f"Sum is {a + b}")

# Formatting:
# pi = 3.14159
# print(f"Pi value: {pi:.2f}")

# from string import Template

# t = Template("My name is $name and I am $age")
# print(t.substitute(name="Chandan", age=20))

'''
if True:
    print("do this")
else:
    print("do that")

output:do this

if []:
    print("do this ")
else:
    print("do that")    

output:do that



import webbrowser
webbrowser.open("www.fackbook.com")
output:open the fackbook in Tab
'''

'''escap character:

print("print\nhello")
output:print
       hello

problem is how to print \n 

\n
\t
\b
\\
\'
\''
\r


print("helloo\b")
output:hello

print("in python \\n is new line")
output:in python \n is new line

raw string:
print(r"hello\n hello")
ourput:hello\n hello

print(""python" is language")
output:error

print("\"python\" is language")
output:"python" is language

print('"python" is language')
output:"python" is language

print('it\'s')
output:it's

import time
for i in range(1,6):
       time.sleep(1)
       print(i,end='\r')
else:
       print("timeout")

output:print 1 to 5 at same place     '''



